#!/bin/bash

CONTROL_HOSTNAME=$(jq < env.json -r '.control_hostname')
CONTROL_IP=$(jq < env.json -r '.control_ip')
REGEX="kubeadm join ${CONTROL_IP}:6443 --token [a-zA-Z0-9.]* --discovery-token-ca-cert-hash sha256:[a-zA-Z0-9]*"
while true; do
	JOIN_CMD=$(ssh "${CONTROL_HOSTNAME}" cat /etc/kubernetes/join-command)
	if [[ ${JOIN_CMD} =~ ${REGEX} ]]; then
		echo "Got valid join command"
		echo "${JOIN_CMD}"
		eval "${JOIN_CMD}"
		break
	else
		echo "Join command not ready. Trying again in 10 seconds"
		sleep 10
	fi
done
