#!/bin/bash

CONTROL_HOSTNAME=$(jq < env.json -r '.control_hostname')
HOSTNAME=$(hostname -s)

# Check whether this node exists as a worker node in the cluster
ssh "${CONTROL_HOSTNAME}" kubectl get nodes | grep "${HOSTNAME}"
if [[ "$?" == 0 ]]; then
	# ssh to control plane and drain this node
	ssh "${CONTROL_HOSTNAME}" kubectl drain "${HOSTNAME}" --delete-emptydir-data --force --ignore-daemonsets

	# Clean up the node here
	kubeadm reset

	# Delete the node from the control plane
	ssh "${CONTROL_HOSTNAME}" kubectl delete node "${HOSTNAME}"
else
	echo "This isn't a worker node in the cluster. Continuing to clean up files"
fi
