#!/bin/bash

systemctl stop etcd kube-scheduler kube-apiserver kube-controller-manager

CUSTOMFILES_DIR="customfiles"
FILE_LIST=()
while IFS= read -d $'\0' -r FILE ; do
	REAL_FILE=$(echo "$FILE" | sed 's/'"${CUSTOMFILES_DIR}"'//')
  FILE_LIST=("${FILE_LIST[@]}" "$REAL_FILE")
done < <(find "${CUSTOMFILES_DIR}" -type f -print0)

for FILE in "${FILE_LIST[@]}"; do
	rm "$FILE"
	echo "rm $FILE"
done
